version: '2'
services:
  nginx:
    image: nginx:1.17
    container_name: dchat-nginx
    ports:
      - "8170:80"
    volumes:
      - "./nginx_config:/etc/nginx/conf.d/"
    depends_on: 
      - server 
  server:
    build: ./docker/golang
    container_name: dchat-server
    working_dir: "/.go/src/github.com/kindai-csg/D-Chat/"
    command: /.go/bin/fresh
    ports:
      - "8180:3000"
    volumes:
      - "./infrastructure:/.go/src/github.com/kindai-csg/D-Chat/infrastructure"
      - "./interfaces:/.go/src/github.com/kindai-csg/D-Chat/interfaces"
      - "./usecase:/.go/src/github.com/kindai-csg/D-Chat/usecase"
      - "./domain:/.go/src/github.com/kindai-csg/D-Chat/domain"
      - "./test:/.go/src/github.com/kindai-csg/D-Chat/test"
      - "./go.mod:/.go/src/github.com/kindai-csg/D-Chat/go.mod"
      - "./go.sum:/.go/src/github.com/kindai-csg/D-Chat/go.sum"
      - "./main.go:/.go/src/github.com/kindai-csg/D-Chat/main.go"
    tty: true
    depends_on: 
      - mongodb 
  mongodb:
    image: mongo:4.2.8
    container_name: dchat-mongodb
    environment:
      - "ME_CONFIG_MONGODB_ADMINUSERNAME=root"
      - "ME_CONFIG_MONGODB_ADMINPASSWORD=example"
    volumes:
      - "./mongodb:/data/db"
